version: "3.8"  # Specify a compatible Docker Compose version

services:
  office-8081:
    image: nttlong/lv-libreoffice:1.11
    container_name: office-8081
    ports:
      - "8084:8080"
    volumes:
      - /mnt/files:/mnt/files
    command: ["8080"]
  pdf-8082:
    image: nttlong/lv-pdf:1
    container_name: pdf-8082
    ports:
      - "8085:8080"
    volumes:
      - /mnt/files:/mnt/files
    command: [ "8080" ]
  video-8083:
    image: nttlong/lv-video:5.1
    container_name: video-8083
    ports:
      - "8086:8080"
    volumes:
      - /mnt/files:/mnt/files
    command: [ "8080" ]
#  tika:
#    image: apache/tika
#    container_name: tika-9998
#    ports:
#      - "9998:9998"
#  video-1111:
#    image: docker.io/nttlong/fs:fs.video.amd.1
#    container_name: video-1111
#    ports:
#      - "1111:1111"
#    volumes:
#      - /socat-share:/socat-share
#  pdf-1112:
#    image: docker.io/nttlong/fs:fs.pdf.amd.2
#    container_name: pdf-1112
#    ports:
#      - "1112:1112"
#    volumes:
#      - /socat-share:/socat-share
#  office:
#    image: docker.io/nttlong/fs:fs.office.amd.1.4
#    container_name: office-1113  # Corrected container name to match command
#    ports:
#      - "1113:1113"
#    volumes:
#      - /socat-share:/socat-share
#  google-drive:
#    image: docker.io/nttlong/fs:fs.google.amd.2
#    container_name: google-drive-1115  # Corrected container name to match command
#    ports:
#      - "1116:1116"
#    volumes:
#      - /socat-share:/socat-share
#  distribute-lock:
#    image: zookeeper
#    container_name: distribute-lock
#    ports:
#      - "2181:2181"
#

#  thumb:
#    image: docker.io/nttlong/fs:fs.thumbs.amd.1
#    container_name: thumb-1114
#    ports:
#      - "1114:1114"
#    volumes:
#      - /mnt/files:/mnt/files
#  memcached:
#    image: memcached
#    container_name: memcached-11211
#    ports:
#      - "11212:11211"

#  web:
#    image: docker.io/nttlong/fs:fs.tiny.amd.19.2
#    container_name: web-8012
#    ports:
#      - "8012:8012"
#    volumes:
#      - /mnt/files:/mnt/files
#    command: ["python3", "/app/cy_xdoc/server.py","private_web_api=http://localhost/lvfile"]
