images:
  web: nttlong/fs:api.apps.amd.1.4
  jobs:
    slim: nttlong/fs:job.apps.slim.amd.1.5
    office: nttlong/fs:job.office.amd.1.2
    ocr: nttlong/fs:job.apps.ai.amd.1.3
    easy_ocr: nttlong/fs:job.apps.ai.amd.1.3
config:
  logs_url: https://hooks.slack.com/services/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




