images:
  web: nttlong/fs:fs.tiny.amd.1.1
  jobs:
    slim: nttlong/fs:fs.slim.amd.1.1
    medium: nttlong/fs:fs.medium.amd.1.1
    large: nttlong/fs:fs.large.amd.1.1


config:
  logs_url: https://hooks.slack.com/services/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




