apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-kube-prometheus-prometheus:9090
