#---
#{{ $info := $.Values.name -}}
#    {{ $dataFile := join "" (list "data/" $info ".yml") -}}
#    {{ $data := .Files.Get $dataFile | fromYaml -}}
#      {{ $fileJob := $data.fileJob -}}
#      {{ $db := $data.config.db -}}
#      {{ $es := $data.config.elastic_search -}}
#      {{ $rb := $data.config.rabbitmq -}}
#      {{ $api := $data.webApi -}}
#      {{ $storage := $data.storage}}
#    {{ $dataJson := toPrettyJson $api -}}
#---
#{{ if $api}}
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: xdoc-office-thumbs
#  namespace: {{$api.namespace}}
#spec:
#
#  selector:
#    matchLabels:
#      app: xdoc-office-thumbs
#  replicas: 4
#  #minimumReplicas: {{$api.replicas}}
#  template:
#    metadata:
#      labels:
#        app: xdoc-office-thumbs
#    spec:
#      containers:
#        - args:
#              - python3
#              - /app/app_services/office_server.py
#          image: docker.io/nttlong/fs:gradio.office.thumbs.amd.1
#          name: xdoc-office-thumbs
#          imagePullPolicy: IfNotPresent
#          ports:
#            - containerPort: 8014
#---
#apiVersion: v1
#kind: Service
#metadata:
# name: xdoc-office-thumbs
# namespace: {{$api.namespace}}
# labels:
#   app: xdoc-office-thumbs
#spec:
# type: NodePort
# selector:
#   app: xdoc-office-thumbs
# ports:
#   - name: "xdoc-office-thumbs-node-port"
#     protocol: TCP
#     port: 8014
#     targetPort: 8014
#---
#{{end}}
#---