---
{{ $info := $.Values.name -}}
    {{ $dataFile := join "" (list "data/" $info ".yml") -}}
    {{ $data := .Files.Get $dataFile | fromYaml -}}
      {{ $fileJob := $data.fileJob -}}
      {{ $db := $data.config.db -}}
      {{ $es := $data.config.elastic_search -}}
      {{ $rb := $data.config.rabbitmq -}}
      {{ $api := $data.webApi -}}
      {{ $msg := $data.msg -}}
      {{ $storage := $data.storage}}
    {{ $dataJson := toPrettyJson $api -}}
---
{{ if $msg}}
---
{{ if $api}}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{$msg.name}}
  namespace: {{$msg.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{$msg.name}}
  template:
    metadata:
      labels:
        app: {{$msg.name}}
    spec:
      containers:
        - name: {{$msg.name}}
          image: rabbitmq:3
          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: {{$msg.name}}-service
  namespace: {{$msg.namespace}}
  labels:
    app: {{$msg.name}}
spec:
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 31674
  selector:
    app: {{$msg.name}}
  type: NodePort
---
{{end}}
---
---
{{end}}
---
