---
{{ $info := $.Values.name -}}
    {{ $dataFile := join "" (list "data/" $info ".yml") -}}
    {{ $data := .Files.Get $dataFile | fromYaml -}}
      {{ $fileJob := $data.fileJob -}}
      {{ $db := $data.config.db -}}
      {{ $es := $data.config.elastic_search -}}
      {{ $rb := $data.config.rabbitmq -}}
      {{ $api := $data.webApi -}}
      {{ $ingress := $data.ingress -}}
      {{ $storage := $data.storage}}
    {{ $dataJson := toPrettyJson $api -}}
---
{{ if $ingress}}
---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1 #networking.k8s.io/v1
metadata:
  name: {{$ingress.name}}
  namespace: {{$ingress.namespace}}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: {{$ingress.path}}
            pathType: Prefix
            backend:
              service:
                name: {{$ingress.servicename}}
                port:
                  number: 8082
status:
  loadBalancer:
    ingress:
      - ip: {{$ingress.host_ip}}
---
{{end}}
---