---
{{ $info := $.Values.name -}}
    {{ $dataFile := join "" (list "data/" $info ".yml") -}}
    {{ $data := .Files.Get $dataFile | fromYaml -}}
      {{ $fileJob := $data.fileJob -}}
      {{ $db := $data.config.db -}}
      {{ $es := $data.config.elastic_search -}}
      {{ $rb := $data.config.rabbitmq -}}
      {{ $api := $data.webApi -}}
      {{ $cache := $data.cache -}}
      {{ $storage := $data.storage -}}
    {{ $dataJson := toPrettyJson $api -}}
---
  {{ if $api}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-cache
  namespace: {{$api.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-cache
  template:
    metadata:
      labels:
        app: file-cache
    spec:
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "xdoc"
          effect: "NoSchedule"
      containers:
      - name: file-cache
        image: memcached:latest
        ports:
        - containerPort: 11211
---
kind: Service
apiVersion: v1
metadata:
  name: memcache-service
  namespace: {{$api.namespace}}
spec:
  ports:
    - name: '11211'
      protocol: TCP
      port: 11211
      targetPort: 11211
      nodePort: 30211
  selector:
    app: file-cache
  type: NodePort
---
{{end}}
---
