---
kind: Namespace
apiVersion: v1
metadata:
  name: lv-dashboard
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dashboard-metrics-scraper
  namespace: lv-dashboard
  labels:
    app: dashboard-metrics-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard-metrics-scraper
  template:
    metadata:
      labels:
        app: dashboard-metrics-scraper
    spec:
      volumes:
        - name: tmp-volume
      containers:
        - name: dashboard-metrics-scraper
          image: kubernetesui/metrics-scraper:v1.0.8
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1001
            runAsGroup: 2001
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: kubernetes-dashboard
      serviceAccount: kubernetes-dashboard
      hostNetwork: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-dashboard
  namespace: lv-dashboard
  labels:
    app: kubernetes-dashboard
rules:
  - verbs:
      - get
      - update
      - delete
    apiGroups:
      - ''
    resources:
      - secrets
    resourceNames:
      - kubernetes-dashboard-key-holder
      - kubernetes-dashboard-certs
      - kubernetes-dashboard-csrf
  - verbs:
      - get
      - update
    apiGroups:
      - ''
    resources:
      - configmaps
    resourceNames:
      - kubernetes-dashboard-settings
  - verbs:
      - proxy
    apiGroups:
      - ''
    resources:
      - services
    resourceNames:
      - heapster
      - dashboard-metrics-scraper
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - services/proxy
    resourceNames:
      - heapster
      - 'http:heapster:'
      - 'https:heapster:'
      - dashboard-metrics-scraper
      - http:dashboard-metrics-scraper
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kubernetes-dashboard
  namespace: lv-dashboard
  labels:
    app: kubernetes-dashboard
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubernetes-dashboard
  namespace: lv-dashboard
  labels:
    app: kubernetes-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-dashboard
  template:
    metadata:
      labels:
        app: kubernetes-dashboard
    spec:
      volumes:
        - name: kubernetes-dashboard-certs
          secret:
            secretName: kubernetes-dashboard-certs
            defaultMode: 420
        - name: tmp-volume
      containers:
        - name: kubernetes-dashboard
          image: kubernetesui/dashboard:v2.6.1
          args:
            - '--auto-generate-certificates'
            - '--namespace=kubernetes-dashboard'
          ports:
            - containerPort: 8443
              protocol: TCP
          volumeMounts:
            - name: kubernetes-dashboard-certs
              mountPath: /certs
            - name: tmp-volume
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1001
            runAsGroup: 2001
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: kubernetes-dashboard
      serviceAccount: kubernetes-dashboard
---
kind: Service
apiVersion: v1
metadata:
  name: kubernetes-dashboard
  namespace: lv-dashboard
  labels:
    k8s-app: kubernetes-dashboard
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
      nodePort: 30036
  selector:
    k8s-app: kubernetes-dashboard

  type: NodePort