namespace: default-99-30041
appConfig:
  name: lv-file
  host:
    path: lvfile
    name: 172.16.7.99
    protocol: https
  nodePort: 30041
db:
  mongodb: mongodb://192.168.18.36:27017
  manage: 'lv-docs'
search:
  prefix_index: 'lv-codx'
  server: 'http://192.168.18.36:9200'
storage:
  server: 192.168.18.36
  directory: /codx-file-storage/files
  name: storage-files