namespace: files
#webAppName: lv-file-dev
appConfig:
  name: lv-file
  host:
    path: lvfile
    name: 172.16.7.99
    protocol: https
  ingress:
    lv-file:
      pathType: Prefix

db:
  mongodb: mongodb://192.168.18.36:27017
  manage: 'lv-docs'
search:
  prefix_index: 'lv-codx'
  server: 'http://192.168.18.36:9200'
storage:
  server: 192.168.18.36
  directory: /codx-file-storage/files
  name: storage-files

replicas: 2
rabbit:
  server: codx-rabbitmq.rabbitmq
  username: codx
  password: Lacviet#123
customer: "qc"
imageTag: "latest"
repository: "docker.lacviet.vn/xdoc"
debugLibs: []
nodePort:
  content: "32260"
  office: "32261"
  pdf: "32263"
  video: "32264"
  tika: "32265"
  ocr: "32266"
  thumbs: "32267"

