from setuptools import setup
from Cython.Build import cythonize
setup(
	ext_modules=cythonize([r'cy_jobs/move_to_disk.py',
		r'cy_jobs/fix_onedrive_sync.py',
		r'cy_jobs/cloud_sync.py',
		r'cy_jobs/google_file_sync.py',
		r'cy_jobs/google_drive.py',
		r'cy_jobs/azure_file_sync.py',
		r'cy_jobs/contents.py',
		r'cy_jobs/cy_job_libs.py',
		r'cy_jobs/ocr.py',
		r'cy_jobs/test.py',
		r'cy_jobs/add_tenat_to_google_api.py',
		r'cy_jobs/contents_delete.py',
		r'cy_jobs/files.py',
		r'cy_jobs/google_directories_sync.py',
		r'cy_jobs/images.py',
		r'cy_jobs/re_do_all.py',
		r'cy_jobs/web.py',
		r'cy_jobs/fix_data/fix_google_drive.py',
		r'cy_jobs/fix_data/fix_mongodb_file.py',
		r'cy_jobs/jobs/task_orc.py',
		r'cy_jobs/jobs/task_vietlot_meta.py',
		r'cy_jobs/jobs/task_google_driver_folders.py',
		r'cy_jobs/jobs/delete_task_google_folder_sync.py',
		r'cy_jobs/jobs/task_google_file_sync.py',
		r'cy_jobs/jobs/task_onedrive_file_sync.py',
		r'cy_jobs/jobs/task_vietlott_ocr_all.py',
		r'cy_jobs/jobs/task_content.py',
		r'cy_jobs/jobs/task_vietllot_sync.py',
		r'cy_jobs/jobs/task_google_file_sync_unfined.py',
		r'cy_jobs/controllers/files_controller.py',
		r'cy_jobs/controllers/base_controller.py',
		r'cy_jobs/controllers/file_pushing_controller.py',
		r'cy_jobs/services/ocrmypdf_service.py'],language_level = '3')
)
