from setuptools import setup
from Cython.Build import cythonize
setup(
	ext_modules=cythonize([r'elasticsearch/transport.py',
		r'elasticsearch/client.py',
		r'elasticsearch/helpers.py',
		r'elasticsearch/connection_pool.py',
		r'elasticsearch/utils.py',
		r'elasticsearch/compat.py',
		r'elasticsearch/serializer.py',
		r'elasticsearch/exceptions.py',
		r'elasticsearch/helpers/errors.py',
		r'elasticsearch/helpers/test.py',
		r'elasticsearch/helpers/actions.py',
		r'elasticsearch/client/remote.py',
		r'elasticsearch/client/nodes.py',
		r'elasticsearch/client/indices.py',
		r'elasticsearch/client/ingest.py',
		r'elasticsearch/client/cluster.py',
		r'elasticsearch/client/utils.py',
		r'elasticsearch/client/snapshot.py',
		r'elasticsearch/client/cat.py',
		r'elasticsearch/client/tasks.py',
		r'elasticsearch/client/xpack/watcher.py',
		r'elasticsearch/client/xpack/monitoring.py',
		r'elasticsearch/client/xpack/ml.py',
		r'elasticsearch/client/xpack/migration.py',
		r'elasticsearch/client/xpack/graph.py',
		r'elasticsearch/client/xpack/security.py',
		r'elasticsearch/client/xpack/deprecation.py',
		r'elasticsearch/client/xpack/license.py',
		r'elasticsearch/connection/base.py',
		r'elasticsearch/connection/pooling.py',
		r'elasticsearch/connection/http_urllib3.py',
		r'elasticsearch/connection/http_requests.py'],language_level = '3')
)
