---
{{ $info := $.Values.name -}}
    {{ $dataFile := join "" (list "data/" $info ".yml") -}}
    {{ $data := .Files.Get $dataFile | fromYaml -}}
      {{ $fileJob := $data.fileJob -}}
      {{ $db := $data.config.db -}}
      {{ $es := $data.config.elastic_search -}}
      {{ $rb := $data.config.rabbitmq -}}
      {{ $api := $data.webApi -}}
      {{ $cache := $data.cache -}}
      {{ $storage := $data.storage -}}
    {{ $dataJson := toPrettyJson $api -}}
---
{{ if $cache }}
---
  {{ if $api}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $cache.name }}
  namespace: {{ $cache.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $cache.name }}
  template:
    metadata:
      labels:
        app: {{ $cache.name }}
    spec:
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "xdoc"
          effect: "NoSchedule"
      containers:
      - name: {{ $cache.name }}
        image: memcached:latest
        ports:
        - containerPort: 11211
---
kind: Service
apiVersion: v1
metadata:
  name: {{ $cache.name }}-service
  namespace: {{ $cache.namespace }}
spec:
  ports:
    - name: '11211'
      protocol: TCP
      port: 11211
      targetPort: 11211
      nodePort: 30911
  selector:
    app: {{ $cache.name }}
  type: NodePort
---
{{end}}
---
{{end}}
---