---
{{ $info := $.Values.name -}}
    {{ $dataFile := join "" (list "data/" $info ".yml") -}}
    {{ $data := .Files.Get $dataFile | fromYaml -}}
      {{ $fileJob := $data.fileJob -}}
      {{ $db := $data.config.db -}}
      {{ $es := $data.config.elastic_search -}}
      {{ $rb := $data.config.rabbitmq -}}
      {{ $api := $data.webApi -}}
      {{ $storage := $data.storage}}
    {{ $dataJson := toPrettyJson $api -}}
---
{{ if $api}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
  #namespace: {{$api.namespace}}
  namespace: xdoc-web
spec:
  selector:
    matchLabels:
      app: tika
  replicas: 1
  #minimumReplicas: {{$api.replicas}}
  template:
    metadata:
      labels:
        app: tika
    spec:
      containers:
        - image: apache/tika:latest
          name: tika
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9998
---
apiVersion: v1
kind: Service
metadata:
 name: tika
 namespace: {{$api.namespace}}
 labels:
   app: tika
spec:
 type: NodePort
 selector:
   app: tika
 ports:
   - name: "tika-nod-port"
     protocol: TCP
     port: 9998
     targetPort: 9998
---
{{end}}
---