---
    {{ $info := $.Values.name -}}
    {{ $dataFile := join "" (list "data/" $info ".yml") -}}
    {{ $data := .Files.Get $dataFile | fromYaml -}}
      {{ $fileJob := $data.fileJob -}}
      {{ $db := $data.config.db -}}
      {{ $es := $data.config.elastic_search -}}
      {{ $rb := $data.config.rabbitmq -}}
      {{ $api := $data.webApi -}}
      {{ $cache := $data.cache -}}
      {{ $msg := $data.msg -}}
    {{ $dataJson := toPrettyJson $api -}}


---
{{ if $api }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{$api.configMapName}}
  namespace: {{$api.namespace}}
data:
  admin_db_name: {{ $db.admin_db_name }}
  db: {{$db.cnn}}
  elastic_search.prefix_index: '{{$es.prefix_index}}'
  elastic_search.server: '{{ $es.server }}'
  rabbitmq.port: '{{ $rb.port }}'
  {{ if $msg }}
  rabbitmq.server: '{{ $msg.name}}.{{$msg.namespace}}'
  {{else}}
  rabbitmq.server: '{{ $rb.server }}'
  {{end}}
  rabbitmq.msg: '{{ $rb.msg }}'
  temp_directory_: /app/share-storage
  {{ if $cache }}
  cache_server: {{$cache.name}}.{{$cache.namespace}}:11211
  {{else}}
  cache_server: memcache-service.file-cache:11211
  {{end}}
  workers: '1'
  worker_class.uvicorn: 'UvicornWorker' #UvicornH11Worker
  worker_class.h11: 'UvicornH11Worker' #UvicornH11Worker
  worker_class.uvloop: 'uvloop'
  worker_class.trio: 'trio'
  timeout_keep_alive: '30'
  timeout_graceful_shutdown: '30'
  server_type.unvicorn: 'unvicorn'
  server_type.hypercorn: 'hypercorn'
  server_type.default: 'auto'
  h2_max_concurrent_streams: '100'
  vn_suggest_url: vn-suggestion.{{$api.namespace}}:8000 #vn-suggestion.xdoc-web:8000 TCP
  tika_server: tika.{{$api.namespace}}:9998
---
{{end}}