---
{{ $info := $.Values.name -}}
    {{ $dataFile := join "" (list "data/" $info ".yml") -}}
    {{ $data := .Files.Get $dataFile | fromYaml -}}
      {{ $fileJob := $data.fileJob -}}
      {{ $db := $data.config.db -}}
      {{ $es := $data.config.elastic_search -}}
      {{ $rb := $data.config.rabbitmq -}}
      {{ $api := $data.webApi -}}
      {{ $storage := $data.storage}}
    {{ $dataJson := toPrettyJson $api -}}
---
{{ if $api}}
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIubGFjdmlldC52biI6eyJ1c2VybmFtZSI6InB1bGwiLCJwYXNzd29yZCI6IkxhY3ZpZXQjMTIzIiwiZW1haWwiOiJwdWxsQGxhY3ZpZXQudm4iLCJhdXRoIjoiY0hWc2JEcE1ZV04yYVdWMEl6RXlNdz09In19fQ==
kind: Secret
metadata:
  name: harbor-secret-registry
  namespace: {{$api.namespace}}
type: kubernetes.io/dockerconfigjson
---
# The first we need deploy an application where Pod of web will run inside
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$api.name}}
  namespace: {{$api.namespace}}
spec:
  selector:
    matchLabels:
      app: {{$api.name}}
  replicas: {{$api.replicas}}
  #minimumReplicas: {{$api.replicas}}
  template:
    metadata:
      labels:
        app: {{$api.name}}
    spec:
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "xdoc"
          effect: "NoSchedule"
      imagePullSecrets:
        - name: harbor-secret-registry
      volumes:
        - name: {{$storage.name}}
          {{if hasKey  $storage "className"}}
          persistentVolumeClaim:
            claimName: {{$storage.name}}
          {{else}}
          nfs:
            server: {{$storage.server}}
            path: {{$storage.directory}}
          {{end}}
      containers:
        - args:
            - python3
            - /app/cy_xdoc/server.py
            - bind=0.0.0.0:80
            - content_segment_len=9
            - host_url='{{$api.hostUrl}}'
            - elastic_search.server=$(elastic_search.server)
            - elastic_search.prefix_index=$(elastic_search.prefix_index)
            - db=$(db)
            - admin_db_name=$(admin_db_name)
            - rabbitmq.server=$(rabbitmq.server)
            - rabbitmq.port=$(rabbitmq.port)
            - rabbitmq.msg=$(rabbitmq.msg)
            - cache_server=$(cache_server)
            - workers=$(workers)
            - server_type=$(server_type.hypercorn)
            - worker_class=$(worker_class.trio)
            - timeout_keep_alive=$(timeout_keep_alive)
            - timeout_graceful_shutdown=$(timeout_graceful_shutdown)
            - h2_max_concurrent_streams=$(h2_max_concurrent_streams)
            - vn_suggest_url=$(vn_suggest_url)
            - tika_server=$(tika_server)
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            readinessProbe:
              httpGet:
                path: /api/healthz
                port: 80
              initialDelaySeconds: 5
              periodSeconds: 10
              failureThreshold: 3
          image: {{$api.repository}}:{{$api.tag}}
          envFrom:
            - configMapRef:
               name: {{$api.configMapName}}
          name: {{$api.name}}
          imagePullPolicy: {{$api.pullPolicy}}
          volumeMounts:
            - mountPath:  {{$api.mountPath}}
              name: {{$storage.name}}
          ports:
            - containerPort: 80
---
{{end}}
---
