apiVersion: v1
kind: Namespace
metadata:
  name: lv-cache

---
apiVersion: v1
kind: Service
metadata:
  name: memcache-service
  namespace: lv-cache
spec:
  type: NodePort
  selector:
    app: memcached
#  ports:
#  - protocol: TCP
#    port: 11211
#    targetPort: 11211
  ports:
    - name: "11211"
#      protocol: TCP
      port: 11211
      targetPort: 11211
      nodePort: 30998
##        servers = ["172.16.7.91:30998"]
##        servers = ["memcache-service.lv-cache:11211"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  namespace: lv-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - name: memcached
        image: memcached:latest
        ports:
        - containerPort: 11211
