{{- define "apps-data"  -}}
{{- $appConfig :=(index .values.appConfig .values.webAppName)  }}
---
apps:
    - name: {{ .values.webAppName }}
      image: {{ .images.main }}
      namespace: {{ .values.namespace}}
      replicas: {{.values.replicas}}
      entrypoint:
        - python3
        - /app/cy_xdoc/server.py
        - bind=0.0.0.0:80
        - content_segment_len=9
        {{if $appConfig.host}}
        - host_url={{$appConfig.host.protocol}}://{{$appConfig.host.name}}/{{$appConfig.host.path}}
        - private_web_api=http://localhost/{{$appConfig.host.path}}
        {{end}}
      service:
        {{ if not (index .values.ingress .values.webAppName) }}
        type: nodePort
        nodePort: 30072
        {{end}}
        {{ if (index .values.ingress .values.webAppName) }}
        {{- $ingress := (index .values.ingress .values.webAppName) }}
        ingress:
          path: {{$appConfig.host.path}}
          pathType: {{$ingress.pathType}}
          ip: {{$appConfig.host.name}}
        {{end}}

      storage:
        name: {{ .values.storage.name}}
        server: {{ .values.storage.server}}
        directory: {{ .values.storage.directory}}
      libs:
        - name: pdf
          image: {{ .images.pdf }}
        - name: thumb
          image: {{ .images.thumb }}
        - name: video
          image: {{ .images.video}}
        - name: office
          image: {{.images.office }}
        - name: tika
          image: {{ .images.tika }}
---
{{- end -}}