{{- define "apps-data"  -}}
{{- $appConfig :=.values.appConfig  }}
{{- $processesMsgConfig:= .images.processesMsgConfig }}
{{ $valuesObject:= .values}}
{{ $imagesObject:= .images}}
---
apps:
    - name: {{ $appConfig.name }}
      image: {{ .images.main }}
      namespace: {{ .values.namespace}}
      replicas: {{.values.replicas}}
      entrypoint:
        - python3
        - /app/cy_xdoc/server.py
        - bind=0.0.0.0:80
        - content_segment_len=9
        - private_web_api=http://{{$appConfig.name}}-service.{{.values.namespace}}:8082/{{$appConfig.host.path}} #test-es-service.test-es-99:8082
        {{if $appConfig.host}}
        - host_url={{$appConfig.host.protocol}}://{{$appConfig.host.name}}/{{$appConfig.host.path}}
        - private_web_api=http://localhost/{{$appConfig.host.path}}
        {{end}}
      service:
        {{ if index $appConfig "nodePort" }}
        type: nodePort
        nodePort: {{$appConfig.nodePort}}
        {{else}}
        {{ if index $appConfig "ingress"}}
        {{- $ingress := $appConfig.ingress }}
        ingress:
          path: {{$appConfig.host.path}}
          pathType: {{$ingress.pathType}}
          ip: {{$appConfig.host.name}}
        {{end}}
        {{end}}
        requireService: {{$appConfig.requireService}}

      storage:
        name: {{ .values.storage.name}}
        server: {{ .values.storage.server}}
        directory: {{ .values.storage.directory}}
      libs:
        - name: pdf
          image: {{ .images.pdf }}
        - name: thumb
          image: {{ .images.thumb }}
        - name: video
          image: {{ .images.video}}
        - name: office
          image: {{.images.office }}
        - name: tika
          image: {{ $imagesObject.tika }}
    {{- range $key, $value := .values.processMsg }}
    {{- $app:= (index $processesMsgConfig $value) }}
    {{ if $app }}
    - name: {{$value}}
      image: {{ $imagesObject.main }}
      namespace: {{ $valuesObject.namespace }}
      replicas: {{$app.replicas}}
      entrypoint:
        {{- range $km,$e := $app.entrypoint }}
        - {{$e}}
        {{- end }}
        - private_web_api=http://{{$appConfig.name}}-service.{{$valuesObject.namespace}}:8082/{{$appConfig.host.path}}
      storage:
        name: {{ $valuesObject.storage.name }}
        server: {{ $valuesObject.storage.server }}
        directory: {{ $valuesObject.storage.directory }}
      libs:
        - name: pdf
          image: {{ $imagesObject.pdf }}
        - name: video
          image: {{ $imagesObject.video }}
        - name: office
          image: {{$imagesObject.office }}
        - name: tika
          image: {{ $imagesObject.tika }}
    {{else}}
    - name: {{$value}}
      isError: True
    {{end}}
    {{- end}}

---
{{- end -}}