---
apiVersion: v1
kind: Service
metadata:
 name: content-service
 namespace: {{.Values.namespace}}
 labels:
   app: content-service
spec:
{{ if (and (hasKey .Values "nodePort") (hasKey .Values.nodePort "content")) }}
 type: NodePort
{{else}}
 type: ClusterIP
{{end}}
 selector:
   app: "content"
 ports:
   - name: "content"
     port: 80
     targetPort: 80
     protocol: TCP
{{ if (and (hasKey .Values "nodePort") (hasKey .Values.nodePort "content")) }}
     nodePort: {{.Values.nodePort.content}}
{{end}}
---
