apiVersion: v1
kind: Namespace
metadata:
  name: tk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
  namespace: tk
  #namespace: xdoc-web
spec:
  selector:
    matchLabels:
      app: tika
  replicas: 1
  #minimumReplicas: {{$api.replicas}}
  template:
    metadata:
      labels:
        app: tika
    spec:
      containers:
        - image: apache/tika:latest
          name: tika
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9998
---
apiVersion: v1
kind: Service
metadata:
 name: tika
 namespace: tk
 labels:
   app: tika
spec:
 type: NodePort
 selector:
   app: tika
 ports:
   - name: "tika-nod-port"
     protocol: TCP
     port: 9998
     targetPort: 9998